[tool.poetry]
name = "deep-eval"
version = "0.1.0"
description = ""
authors = ["Mattan Yeroushalmi <mattan.yeroushalmi@similarweb.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
deepeval = "^1.1.4"
transformers = "^4.44.2"
torch = "^2.4.1"
accelerate = "^0.34.2"
mlx-lm = "^0.18.1"
ollama = "^0.3.2"
pandas = "^2.2.2"
asyncio = "^3.4.3"
beautifulsoup4 = "4.12.3"
selenium = "4.22.0"
requests = "2.32.3"
colorama = "^0.4.6"
scikit-learn = "^1.5.2"
py-readability-metrics = "^1.4.5"
langchain = "^0.3.23"
langchain-openai = "^0.3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
